### ISSUE TITLE
UI for USGS REST service

### ISSUE THREAD

**Issue by Ameya05** [GeoGateway/geogateway-portal#21]
Develop a user interface that allows someone to view seismicity data from the [USGS REST](https://earthquake.usgs.gov/fdsnws/event/1/) service on the main GeoGateway map.

**Comment by Ameya05** [comment]
Initial Seismicity code is already present in the file at -  geogateway-portal/html/js/anss-service.js 
However, the query url is not dynamic at the moment.

To-do : 
1. Take input parameters from the UI and pass it to the query.
2. Provide interactivity in the displayed map data such that user can view certain details on click of a marker on map.

**Comment by marpierc** [comment]
See https://earthquake.usgs.gov/fdsnws/event/1/ for the new API

**Comment by Ameya05** [comment]
To-Do: 

1. Either stick to the KML since it provides inherent interactivity on google map or Work with the GeoJSON format and make it interactive. GeoJSON provides point markers on maps. These markers can be colored based on the earthquake intensity and on click of these markers, the info can be shown.
2. Add input hints such as date format, max min latitude / longitude values, timezone etc
3. Basic input validation on the UI.
4. No data handling?
